server:
  port: 8081
  servlet:
    context-path: /test-task/ticket-service
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: ticket-application
  datasource:
    password: tarelka12345
    url: jdbc:postgresql://localhost:5432/ticket-service
    username: postgres
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
